### PR TITLE
Add plugin and theme command

### LINKED ISSUE #24: Add plugin and theme command
Originally https://github.com/wp-cli/wp-cli/issues/3782

From @grappler https://github.com/wp-cli/wp-cli/issues/3782#issue-203636453:
> We use WP-CLI to install and update translations which works great. The command also installs the theme and plugin translations.
> 
> I wanted to see which translations were installed for which plugins. This would be a great extension of the feature.

From @danielbachhuber https://github.com/wp-cli/wp-cli/issues/3782#issuecomment-293313994:

> After `wp core language` is split out to `wp language core` in #3728, we should add `wp language (plugin|theme)` for plugin and theme language management.

From @schlessera https://github.com/wp-cli/wp-cli/issues/3782#issuecomment-328913851:

> Apparently, when you run `wp language core`, WP takes care of updating plugins and themes language files automatically now.
> 
> We'd probably need to set this filter: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-language-pack-upgrader.php#L74-L82
> 
> I just think that WP-CLI should be very explicit about what it does, and what it doesn't. It is okay for WP to hook into an admin backend button click and do some magic. But I don't think that WP-CLI should do that sort of magic as well.

### PR DESCRIPTION
**Pull request by swissspidy**
This fixes #24 (originally https://github.com/wp-cli/wp-cli/issues/3782).

Things that still needs to be done/decided, among others:

* [x] ~Decide whether `wp language plugin install hello-dolly en_GB` would accept an `--activate` flag.  
  Activating a language is a global action per site. One cannot activate language X for plugin A and language Y for plugin B. Hence, I think only the core command should allow activating languages.~ The answer is _no_. Activating a language should be separate.
* [x] Implement `uninstall` commands.  
  `\WP_CLI\CommandWithTranslation::uninstall()` currently respects the object type, but doesn't know about the plugin/theme slug. 
* [x] Implement `update` commands.  
  `\WP_CLI\CommandWithTranslation::update()` currently updates _all_ translations.  
  ~Should `wp language core update` only update translations for core and `wp language plugin update` for plugins (or a specific plugin?).~  
  The answer is _yes_. If someone wants to update all files, they can use something like `for type in core plugin theme; do wp language $type update; done`

### CODE REVIEW

**Comment by schlessera** [comment]
> Decide whether wp language plugin install hello-dolly en_GB would accept an --activate flag.

Shouldn't we rather have a `wp site switch-language` or `wp language switch` instead? I also think that `switch` is a better term, as activating one automatically deactivates the previous one.

> Implement uninstall commands.

Yes, that would be useful. Maybe we should also add a sort of `--prune` switch, that uninstall all non-active languages.

> Implement update commands.
> Should wp language core update only update translations for core and wp language plugin update for plugins (or a specific plugin?).

Yes, I still maintain that WP-CLI should be completely explicit about what it does and what it doesn't do.

**Comment by swissspidy** [comment]
> Shouldn't we rather have a `wp site switch-language` or `wp language switch` instead? I also think that `switch` is a better term, as activating one automatically deactivates the previous one.

This sounds reasonable and I think can be worked on in a separate PR. I'll create a new issue for this.

> Maybe we should also add a sort of `--prune` switch, that uninstall all non-active languages.

I think I'll create a separate issue for this as well.

> Yes, I still maintain that WP-CLI should be completely explicit about what it does and what it doesn't do.

This would result in the following commands:

* `wp language core update`
* `wp language plugin update`
* `wp language theme update`

What about one command that does all of the above? Like `wp language core update` currently does`.

**Comment by swissspidy** [comment]
Looks like the cache for plugin and theme languages isn't working. Ugh.

**Comment by gitlost** [comment]
Re https://github.com/wp-cli/language-command/pull/21#issuecomment-354548541 and slack https://wordpress.slack.com/archives/C02RP4T41/p1516372158000268

That particular issue is to do with the name of the download. If no slug is available then `default` is used, so this test would pass:
```
    When I run `ls {SUITE_CACHE_DIR}/translation`
    Then STDOUT should match /\bplugin-(?:hello-dolly|default)-(?:\d+\.)+\d+-de_DE-\d+\.zip\b/
    And STDOUT should match /\bplugin-(?:hello-dolly|default)-(?:\d+\.)+\d+-en_GB-\d+\.zip\b/
```

**Comment by swissspidy** [comment]
Thanks! I should have thought of that.

Now I just need to figure out how to make sure there's always a slug for plugins, otherwise they cannot be distinguished.

**Comment by swissspidy** [comment]
Alright, 884337b0edd82b9fc2334820059af962800ad65e should fix the caching part. Now looking at the other bugs…

**Comment by gitlost** [comment]
Great progress on this @swissspidy !

I'm going to take the liberty of pushing:

Update test framework to latest.

Use `ja` instead of `en_NZ` for compat with old WP versions in `language-core.feature` and remove refs to `az` as not needed and confusing, `ar` suffices. (These pre-date this PR.)

Add test for `core update` by restricting to one Travis job and using Scenario Outline to iterate over WP versions. This can be used as a template for testing `plugin update` and `theme update` as well (hopefully, if it works!).

Fix `CommandWithTranslation::update()` to append updates so tests pass.

Just on the `dry-run` message `'Available %d translations updates:'`, which pre-dates this PR, we should be able to come up with something nicer than that!

**Comment by schlessera** [comment]
Create a new issue for the dry run message discussion: https://github.com/wp-cli/language-command/issues/25

**Pull request merged**
