### PR TITLE
Add plugin and theme command.

### LINKED ISSUE #24: Add plugin and theme command
Originally https://github.com/wp-cli/wp-cli/issues/3782

From @grappler https://github.com/wp-cli/wp-cli/issues/3782#issue-203636453:
> We use WP-CLI to install and update translations which works great. The command also installs the theme and plugin translations.
> 
> I wanted to see which translations were installed for which plugins. This would be a great extension of the feature.

From @danielbachhuber https://github.com/wp-cli/wp-cli/issues/3782#issuecomment-293313994:

> After `wp core language` is split out to `wp language core` in #3728, we should add `wp language (plugin|theme)` for plugin and theme language management.

From @schlessera https://github.com/wp-cli/wp-cli/issues/3782#issuecomment-328913851:

> Apparently, when you run `wp language core`, WP takes care of updating plugins and themes language files automatically now.
> 
> We'd probably need to set this filter: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-language-pack-upgrader.php#L74-L82
> 
> I just think that WP-CLI should be very explicit about what it does, and what it doesn't. It is okay for WP to hook into an admin backend button click and do some magic. But I don't think that WP-CLI should do that sort of magic as well.

### PR DESCRIPTION
**Pull request by gitlost**
Closes #24 

Restored from https://github.com/wp-cli/language-command/pull/21 after revert https://github.com/wp-cli/language-command/pull/28

Original @swissspidy:

This fixes #24 (originally https://github.com/wp-cli/wp-cli/issues/3782).

Things that still needs to be done/decided, among others:

* [x] ~Decide whether `wp language plugin install hello-dolly en_GB` would accept an `--activate` flag.  
  Activating a language is a global action per site. One cannot activate language X for plugin A and language Y for plugin B. Hence, I think only the core command should allow activating languages.~ The answer is _no_. Activating a language should be separate.
* [x] Implement `uninstall` commands.  
  `\WP_CLI\CommandWithTranslation::uninstall()` currently respects the object type, but doesn't know about the plugin/theme slug. 
* [x] Implement `update` commands.  
  `\WP_CLI\CommandWithTranslation::update()` currently updates _all_ translations.  
  ~Should `wp language core update` only update translations for core and `wp language plugin update` for plugins (or a specific plugin?).~  
  The answer is _yes_. If someone wants to update all files, they can use something like `for type in core plugin theme; do wp language $type update; done`

### CODE REVIEW

**Comment by gitlost** [comment]
See also https://github.com/wp-cli/language-command/issues/27

**Comment by schlessera** [comment]
Tests currently broken due to https://github.com/wp-cli/language-command/issues/37

**Comment by swissspidy** [comment]
@schlessera I thought there were still some things missing, hence the revert in #28? Or do you want to work on that in future iterations?

**Comment by schlessera** [comment]
Well, you made some changes, and it looked complete to me. Are there things you think are missing/incomplete/broken?

**Comment by swissspidy** [comment]
No, not really. Besides these changes I made, I can't remember what else specifically was missing or incomplete back in January. #28 was a bit vague :-)

I'll work on #27 though, and maybe #22.

**Comment by schlessera** [comment]
#27 seems important, as I just had that issue without knowing what was going on.

**Comment by schlessera** [comment]
What does not work as we had initially discussed is that operations like `update` automatically work across all plugins/themes and language packs are always downloaded in their latest version, irregardless of what version of the plugin/theme is installed.

But I think of these are limitations of the infrastructure that we cannot easily get around, aren't they?

**Comment by swissspidy** [comment]
Ah. I'll try to test this locally. Maybe we can find a workaround if that's still an issue.

It would be great to have this documented in the tests somehow.

**Pull request merged**
